import { Header } from "@components/entities";
import CssBaseline from "@mui/material/CssBaseline";
import { Theme } from "@providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CssBaseline />
      <html lang="en">
        <body>
          <Theme>
            <Header />
            {children}
          </Theme>
        </body>
      </html>
    </>
  );
}
